
DROP TABLE IF EXISTS VUELOS;
CREATE TABLE IF NOT EXISTS VUELOS(
ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
,ORIGEN VARCHAR(50)
,DESTINO VARCHAR(50)
,FECHA VARCHAR(20)
,CLASE_VUELO VARCHAR(20)
,HORA_SALIDA VARCHAR(10)
,HORA_LLEGADA VARCHAR(10)
,PRECIO INTEGER
,EQUIPAJE_PERMITIDO VARCHAR(200)
);

INSERT INTO VUELOS(ORIGEN,DESTINO,FECHA,CLASE_VUELO,HORA_SALIDA,HORA_LLEGADA,PRECIO,EQUIPAJE_PERMITIDO) 
            VALUES('CUENCA','QUITO','29/05/2023','ECONOMICA','9:00','9:40',90,'1 BOLSO O MOCHILA PEQUEÑO,1 EQUIPAJE DE BODEGA (20 KG)');

INSERT INTO VUELOS(ORIGEN,DESTINO,FECHA,CLASE_VUELO,HORA_SALIDA,HORA_LLEGADA,PRECIO,EQUIPAJE_PERMITIDO) 
            VALUES('GUAYAQUIL','CIUDAD DE PANAMA','28/02/2023','EJECUTIVA','12:00','14:30',170,'1 BOLSO O MOCHILA PEQUEÑO,1 EQUIPAJE DE MANO (10 KG),2 EQUIPAJE DE BODEGA (20 KG)');

SELECT * FROM VUELOS;