DROP TABLE IF EXISTS VUELOS;
CREATE TABLE IF NOT EXISTS VUELOS(
ID_VUELOS INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
,DESDE VARCHAR(100)
,HASTA VARCHAR(100)
,FECHA VARCHAR(100)
,PRECIO VARCHAR(100)
,DURACION VARCHAR(100)
,CLASE_VUELO VARCHAR(100)
,HORA_SALIDA VARCHAR(100)
,HORA_LLEGADA VARCHAR(100)
);
INSERT INTO VUELOS(DESDE,HASTA,FECHA,PRECIO,DURACION,CLASE_VUELO,HORA_SALIDA,HORA_LLEGADA) 
VALUES('MANTA','QUITO','26/02/2023','43','40','ECONOMICA','6:00','13:00');
INSERT INTO VUELOS(DESDE,HASTA,FECHA,PRECIO,DURACION,CLASE_VUELO,HORA_SALIDA,HORA_LLEGADA) 
VALUES('GUAYAQUIL','QUITO','28/02/2023','36','50','EJECUTIVA','8:00','10:00');
INSERT INTO VUELOS(DESDE,HASTA,FECHA,PRECIO,DURACION,CLASE_VUELO,HORA_SALIDA,HORA_LLEGADA) 
VALUES('QUITO','LOJA','30/02/2023','57','160','ECONOMICA','5:00','7:00');
SELECT *FROM VUELOS;

SELECT DESDE FROM VUELOS;